FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of your app
COPY . .

# Expose port for Nuxt dev server
EXPOSE 3000

# Start dev server
CMD ["npm", "run", "dev"]